FROM apache/airflow:2.9.3-python3.10

USER root
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk-headless \
    && rm -rf /var/lib/apt/lists/*

USER airflow

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

RUN python -m pip install --user pyspark==3.5.0 findspark azure-storage-blob python-dotenv